export const DefaultTheme = {
  palette: {
    themePrimary: "#0061e0",
    themeLighterAlt: "#000409",
    themeLighter: "#001024",
    themeLight: "#001d43",
    themeTertiary: "#003a87",
    themeSecondary: "#0056c5",
    themeDarkAlt: "#176fe3",
    themeDark: "#3884e8",
    themeDarker: "#69a2ee",
    neutralLighterAlt: "#f1f1f8",
    neutralLighter: "#ededf4",
    neutralLight: "#e4e3ea",
    neutralQuaternaryAlt: "#d4d3da",
    neutralQuaternary: "#cacad0",
    neutralTertiaryAlt: "#c2c2c8",
    neutralTertiary: "#a19f9d",
    neutralSecondary: "#605e5c",
    neutralPrimaryAlt: "#3b3a39",
    neutralPrimary: "#323130",
    neutralDark: "#201f1e",
    black: "#000000",
    white: "#f8f7ff",
  },
};
export const DarkModeTheme = {
  palette: {
    themePrimary: "#d2d0ce",
    themeLighterAlt: "#d6d4d2",
    themeLighter: "#dbd9d8",
    themeLight: "#e0dfdd",
    themeTertiary: "#e5e4e3",
    themeSecondary: "#eae9e8",
    themeDarkAlt: "#efefee",
    themeDark: "#f4f4f3",
    themeDarker: "#f9f9f9",
    neutralLighterAlt: "#2b2928",
    neutralLighter: "#333231",
    neutralLight: "#41403e",
    neutralQuaternaryAlt: "#4a4846",
    neutralQuaternary: "#514f4d",
    neutralTertiaryAlt: "#6f6c6a",
    neutralTertiary: "#fcfbfa",
    neutralSecondary: "#fcfbfb",
    neutralPrimaryAlt: "#fdfcfc",
    neutralPrimary: "#faf9f8",
    neutralDark: "#fefefd",
    black: "#fefefe",
    white: "#201f1e",
  },
};

export const HighContrastTheme = {
  palette: {
    themePrimary: "#00fcd7",
    themeLighterAlt: "#000a09",
    themeLighter: "#002822",
    themeLight: "#004c40",
    themeTertiary: "#009781",
    themeSecondary: "#00debd",
    themeDarkAlt: "#19fddb",
    themeDark: "#3dfde0",
    themeDarker: "#70fee8",
    neutralLighterAlt: "#06070b",
    neutralLighter: "#0b0e15",
    neutralLight: "#151925",
    neutralQuaternaryAlt: "#1b202f",
    neutralQuaternary: "#212737",
    neutralTertiaryAlt: "#3b4359",
    neutralTertiary: "#c8c8c8",
    neutralSecondary: "#d0d0d0",
    neutralPrimaryAlt: "#dadada",
    neutralPrimary: "#ffffff",
    neutralDark: "#f4f4f4",
    black: "#f8f8f8",
    white: "#000000",
  },
};

export const MSWordTheme = {
  palette: {
    themePrimary: "#a5b9d1",
    themeLighterAlt: "#070708",
    themeLighter: "#1a1e21",
    themeLight: "#32373f",
    themeTertiary: "#636f7d",
    themeSecondary: "#91a3b8",
    themeDarkAlt: "#adbfd6",
    themeDark: "#b9c9dc",
    themeDarker: "#cad6e5",
    neutralLighterAlt: "#17457e",
    neutralLighter: "#1d4b83",
    neutralLight: "#26548b",
    neutralQuaternaryAlt: "#2c5a91",
    neutralQuaternary: "#325e95",
    neutralTertiaryAlt: "#4b74a7",
    neutralTertiary: "#ecf2fc",
    neutralSecondary: "#eff4fc",
    neutralPrimaryAlt: "#f2f6fd",
    neutralPrimary: "#e3ecfa",
    neutralDark: "#f9fbfe",
    black: "#fcfdfe",
    white: "#124078",
  },
};

export const PowerpointTheme = {
  palette: {
    themePrimary: "#edebe9",
    themeLighterAlt: "#efedeb",
    themeLighter: "#f1efed",
    themeLight: "#f3f1f0",
    themeTertiary: "#f5f4f2",
    themeSecondary: "#f7f6f5",
    themeDarkAlt: "#f9f8f7",
    themeDark: "#fbfafa",
    themeDarker: "#fdfdfc",
    neutralLighterAlt: "#ac3020",
    neutralLighter: "#af3727",
    neutralLight: "#b54131",
    neutralQuaternaryAlt: "#b84738",
    neutralQuaternary: "#bb4d3e",
    neutralTertiaryAlt: "#c76659",
    neutralTertiary: "#c8c8c8",
    neutralSecondary: "#d0d0d0",
    neutralPrimaryAlt: "#dadada",
    neutralPrimary: "#ffffff",
    neutralDark: "#f4f4f4",
    black: "#f8f8f8",
    white: "#a92b1a",
  },
};
export const PurpleTheme = {
  palette: {
    themePrimary: "#d9aefc",
    themeLighterAlt: "#c19be1",
    themeLighter: "#a988c5",
    themeLight: "#9275a9",
    themeTertiary: "#7a628d",
    themeSecondary: "#624e72",
    themeDarkAlt: "#4a3b56",
    themeDark: "#32283a",
    themeDarker: "#1a151e",
    neutralLighterAlt: "#6700f8",
    neutralLighter: "#6600f4",
    neutralLight: "#6200ea",
    neutralQuaternaryAlt: "#5b00da",
    neutralQuaternary: "#5700d0",
    neutralTertiaryAlt: "#5300c8",
    neutralTertiary: "#c8c8c8",
    neutralSecondary: "#d0d0d0",
    neutralPrimaryAlt: "#dadada",
    neutralPrimary: "#ffffff",
    neutralDark: "#f4f4f4",
    black: "#f8f8f8",
    white: "#6a00ff",
  },
};
export const BlackYellowTheme = {
  palette: {
    themePrimary: "#ffff00",
    themeLighterAlt: "#0a0a00",
    themeLighter: "#292900",
    themeLight: "#4d4d00",
    themeTertiary: "#999900",
    themeSecondary: "#e0e000",
    themeDarkAlt: "#ffff19",
    themeDark: "#ffff3d",
    themeDarker: "#ffff70",
    neutralLighterAlt: "#20210f",
    neutralLighter: "#282a14",
    neutralLight: "#37391d",
    neutralQuaternaryAlt: "#404223",
    neutralQuaternary: "#474928",
    neutralTertiaryAlt: "#656841",
    neutralTertiary: "#fffff3",
    neutralSecondary: "#fffff5",
    neutralPrimaryAlt: "#fffff7",
    neutralPrimary: "#ffffed",
    neutralDark: "#fffffb",
    black: "#fffffd",
    white: "#16170a",
  },
};

export const MSTeamsTheme = {
  palette: {
    themePrimary: "#6264a7",
    themeLighterAlt: "#f7f7fb",
    themeLighter: "#e1e1f1",
    themeLight: "#c8c9e4",
    themeTertiary: "#989ac9",
    themeSecondary: "#7173b0",
    themeDarkAlt: "#585a95",
    themeDark: "#4a4c7e",
    themeDarker: "#37385d",
    neutralLighterAlt: "#f3f2f1",
    neutralLighter: "#efeeed",
    neutralLight: "#e5e4e3",
    neutralQuaternaryAlt: "#d6d5d4",
    neutralQuaternary: "#cccbca",
    neutralTertiaryAlt: "#c4c3c2",
    neutralTertiary: "#b6b7c9",
    neutralSecondary: "#777992",
    neutralPrimaryAlt: "#464760",
    neutralPrimary: "#33344a",
    neutralDark: "#272838",
    black: "#1d1d29",
    white: "#faf9f8",
  },
};
